
GET http://localhost:5000/api/orders/621cb41c4b8114e03103e18d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ1NWJmYzkzOGMyZGM2YjIwYzAwNSIsImlhdCI6MTY0NTEwMjUxMSwiZXhwIjoxNjQ4NTU4NTExfQ.ZBBd20W7o4mUZ3kaS8XfF_cRqT1wTE0La4vExAwtEa0
###
