// @ GET all the products
GET http://localhost:5000/api/products
Accept: application/json
Content-Type: application/json
###

// @ GET single product
GET http://localhost:5000/api/products/61ed55c0c938c2dc6b20c007
Accept: application/json
Content-Type: application/json
###


// @ POST for create product
POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmM4YjZkOWY1N2NkNGI4MTdiNzg3NiIsImlhdCI6MTY0NzExNTk4NCwiZXhwIjoxNjUwNTcxOTg0fQ.nK34z3mruGkEAz8kMgZLuwo5rWmmiRobeY2zlm5xngA

###

// @ PUT for update product
GET http://localhost:5000/api/products/61ed55c0c938c2dc6b20c007
Accept: application/json
Content-Type: application/json
###
