// @ Get authentification user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
 "email": "mathieu@exemple.com",
 "password": "1212"
}

###

// @ Get authentification user (admin)
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
 "email": "admin@exemple.com",
 "password": "abcdef"
}

###

# Get all Users
# GET METHOD
GET http://localhost:5000/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjUzYTYwYjQ4ZTcwZTQ0ZGEzNTU3OSIsImlhdCI6MTY0NjYwNjk0NCwiZXhwIjoxNjUwMDYyOTQ0fQ.wGL3_47nQTd1g2mIIQmrfeUU_5sPGooeEUNgTcsIMtc

###


# Find user profile
# GET METHOD
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ1NWJmYzkzOGMyZGM2YjIwYzAwNSIsImlhdCI6MTY0NTEwMjUxMSwiZXhwIjoxNjQ4NTU4NTExfQ.ZBBd20W7o4mUZ3kaS8XfF_cRqT1wTE0La4vExAwtEa0

###


# Create Users
# POST METHOD
POST http://localhost:5000/api/users/
Content-Type: application/json

{
    "name": "Test4",
    "email": "test4@exemple.fr",
    "password" : "abcdef"
}

###

# Update Users
# PUT METHOD
PUT http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ1NWJmYzkzOGMyZGM2YjIwYzAwNSIsImlhdCI6MTY0NTEwMjUxMSwiZXhwIjoxNjQ4NTU4NTExfQ.ZBBd20W7o4mUZ3kaS8XfF_cRqT1wTE0La4vExAwtEa0

{
    "name": "Jeannotte"
}

###

# Delete User
# DELETED METHOD
DELETE http://localhost:5000/api/users/62261c981b3e6e5d45bd8b3e
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjUzYTYwYjQ4ZTcwZTQ0ZGEzNTU3OSIsImlhdCI6MTY0NjYwNjk0NCwiZXhwIjoxNjUwMDYyOTQ0fQ.wGL3_47nQTd1g2mIIQmrfeUU_5sPGooeEUNgTcsIMtc

###