// @ Get authentification user
POST http://localhost:5000/api/users/login
Content-Type: application/json

{
 "email": "admin@exemple.fr",
 "password": "abcdef"
}

###

# Get all Users
# GET METHOD
GET http://localhost:5000/api/users
Content-Type: application/json

###


# Find user profile
# GET METHOD
GET http://localhost:5000/api/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZWQ1NWJmYzkzOGMyZGM2YjIwYzAwMyIsImlhdCI6MTY0NDcwMDY0MywiZXhwIjoxNjQ4MTU2NjQzfQ.dzerBASClIku5NcXWjB8FjgXQ1Ul7eSHN_53hgDrNEE

###


# Create Users
# POST METHOD
POST http://localhost:5000/api/users/
Content-Type: application/json

{
    "name": "Mathieu",
    "email": "mathieu.elisa@gmail.com",
    "password" : "abcdef"
}

###

# Update Users
# PUT METHOD
PUT http://localhost:5000/api/users/profile
Content-Type: application/json

{
    "name": "Mathieu"
}

###


